//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t * createNode(int32_t data);
void deleteList(int32_t ** head);
void displayList(int32_t * head);
void insertAtBeginning(int32_t ** head, uint32_t data);

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linekd_list.c
// Address range: 0x401166 - 0x4011b5
// Line range:    11 - 20
int32_t * createNode(int32_t data) {
    int64_t * mem = malloc(16); // 0x401176
    if (mem != NULL) {
        // 0x40119a
        *(int32_t *)mem = data;
        *(int64_t *)((int64_t)mem + 8) = 0;
        return (int32_t *)mem;
    }
    // 0x401186
    puts("Memory allocation failed.");
    exit(1);
    // UNREACHABLE
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linekd_list.c
// Address range: 0x4011b5 - 0x4011ef
// Line range:    23 - 27
void insertAtBeginning(int32_t ** head, uint32_t data) {
    int64_t v1 = (int64_t)createNode(data); // 0x4011c9
    *(int64_t *)(v1 + 8) = (int64_t)data;
    *(int64_t *)head = v1;
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linekd_list.c
// Address range: 0x4011ef - 0x40123c
// Line range:    30 - 37
void displayList(int32_t * head) {
    // 0x4011ef
    if (head == NULL) {
        // 0x40122f
        puts("NULL");
        return;
    }
    printf("%d -> ", (int64_t)*head);
    int64_t v1 = *(int64_t *)((int64_t)head + 8); // 0x401220
    int32_t * v2 = (int32_t *)v1; // 0x40122d
    while (v1 != 0) {
        // 0x401205
        printf("%d -> ", (int64_t)*v2);
        v1 = *(int64_t *)((int64_t)v2 + 8);
        v2 = (int32_t *)v1;
    }
    // 0x40122f
    puts("NULL");
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linekd_list.c
// Address range: 0x40123c - 0x40128a
// Line range:    40 - 49
void deleteList(int32_t ** head) {
    if (head == NULL) {
        // 0x40127c
        *(int64_t *)head = 0;
        return;
    }
    int32_t * v1 = (int32_t *)head; // 0x40123c
    int64_t v2 = *(int64_t *)((int64_t)v1 + 8); // 0x401259
    free((int64_t *)v1);
    v1 = (int32_t *)v2;
    while (v2 != 0) {
        // 0x401255
        v2 = *(int64_t *)((int64_t)v1 + 8);
        free((int64_t *)v1);
        v1 = (int32_t *)v2;
    }
    // 0x40127c
    *(int64_t *)head = 0;
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linekd_list.c
// Address range: 0x40128a - 0x401305
// Line range:    51 - 69
int main() {
    int32_t * v1 = NULL; // bp-16, 0x401292
    insertAtBeginning(&v1, 3);
    insertAtBeginning(&v1, 5);
    insertAtBeginning(&v1, 7);
    printf("Linked List: ");
    displayList(v1);
    deleteList(&v1);
    puts("Linked list deleted.");
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 5

