//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/function_pointer.c
// Address range: 0x401166 - 0x40121f
// Line range:    13 - 25
int main() {
    // 0x401166
    srand(time(NULL));
    printf("x = %d, y = %d\n\n", (int64_t)(rand() % 100), (int64_t)(rand() % 100));
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 1

