//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/integer_average.c
// Address range: 0x401136 - 0x40122c
// Line range:    3 - 21
int main() {
    // 0x401136
    printf("The numbers: ");
    int32_t v1 = 0; // 0x4011c6
    for (int64_t i = 0; i < 10; i++) {
        // 0x4011a3
        int64_t v2; // bp-8, 0x401136
        int32_t * v3 = (int32_t *)((int64_t)&v2 - 64 + 4 * i); // 0x4011a8
        printf("%d ", (int64_t)*v3);
        v1 += *v3;
    }
    // 0x4011d3
    putchar(10);
    printf("Sum of the entered numbers: %d\n", 0);
    printf("Average of the entered numbers: %d\n", (int64_t)(v1 / 10));
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 1

