//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

int32_t binarySearch(int32_t * arr, int32_t left, int32_t right, int32_t target);

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/binary_search.c
// Address range: 0x401126 - 0x4011b0
// Line range:    4 - 23
int32_t binarySearch(int32_t * arr, int32_t left, int32_t right, int32_t target) {
    int32_t result = -1; // 0x4011a7
    if (right < left) {
      lab_0x4011ae_2:
        // 0x4011ae
        return result;
    }
    int32_t v1 = right;
    int32_t v2 = v1 - left; // 0x40113c
    int32_t v3 = (v2 + (int32_t)(v2 < 0) >> 1) + left; // 0x40114d
    uint32_t v4 = *(int32_t *)(4 * (int64_t)v3 + (int64_t)arr); // 0x401166
    result = v3;
    if (v4 == target) {
        return result;
    }
    int32_t v5; // 0x40119b
    while ((int64_t)target <= (int64_t)v4) {
        // 0x401198
        v5 = v3 - 1;
        result = -1;
        if (v5 < left) {
            return result;
        }
        v1 = v5;
        v2 = v1 - left;
        v3 = (v2 + (int32_t)(v2 < 0) >> 1) + left;
        v4 = *(int32_t *)(4 * (int64_t)v3 + (int64_t)arr);
        result = v3;
        if (v4 == target) {
            return result;
        }
    }
    int32_t v6 = v3 + 1; // 0x401190
    while (v1 >= v6) {
        int32_t v7 = v6;
        v2 = v1 - v7;
        v3 = (v2 + (int32_t)(v2 < 0) >> 1) + v7;
        v4 = *(int32_t *)(4 * (int64_t)v3 + (int64_t)arr);
        result = v3;
        if (v4 == target) {
            return result;
        }
        while ((int64_t)target <= (int64_t)v4) {
            // 0x401198
            v5 = v3 - 1;
            result = -1;
            if (v5 < v7) {
                return result;
            }
            v1 = v5;
            v2 = v1 - v7;
            v3 = (v2 + (int32_t)(v2 < 0) >> 1) + v7;
            v4 = *(int32_t *)(4 * (int64_t)v3 + (int64_t)arr);
            result = v3;
            if (v4 == target) {
                return result;
            }
        }
        // 0x40118d
        v6 = v3 + 1;
    }
    // 0x4011ae
    return -1;
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/binary_search.c
// Address range: 0x4011b0 - 0x401259
// Line range:    26 - 36
int main() {
    int64_t v1 = 2; // bp-56, 0x4011b8
    uint32_t v2 = binarySearch((int32_t *)&v1, 0, 7, 10); // 0x401217
    if (v2 != -1) {
        // 0x40123b
        printf("Element %d is present at index %d\n", 10, (int64_t)v2);
    } else {
        // 0x401225
        printf("Element %d is not present in the array\n", 10);
    }
    // 0x401252
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 2

