//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;

// ------------------- Function Prototypes --------------------

float64_t sqrtNewtonRaphson(float64_t number);

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/calc_2.c
// Address range: 0x401126 - 0x4011c3
// Line range:    6 - 18
float64_t sqrtNewtonRaphson(float64_t number) {
    int64_t v1 = __asm_movsd((int128_t)(int32_t)(float32_t)number); // 0x40112a
    int64_t v2 = __asm_movsd(__asm_movsd_1(0x3ee4f8b588e368f1)); // 0x401137
    int64_t v3 = __asm_movsd(__asm_divsd(__asm_movsd_1(v1), __asm_movsd_1(0x4000000000000000))); // 0x40114d
    int64_t v4 = __asm_movsd(__asm_movsd_1(0x3ff0000000000000)); // 0x40115a
    int128_t v5 = (float32_t)(float64_t)v2; // 0x4011ab
    __asm_comisd(__asm_movsd_1(v4), v5);
    bool v6; // 0x401126
    if (v6 || v6) {
        // 0x4011b2
        return (int64_t)__asm_movq_2(__asm_movq(__asm_movsd_1(v3)));
    }
    int64_t v7 = v3; // 0x4011b0
    while (true) {
        int64_t v8 = v7;
        int128_t v9 = __asm_addsd(__asm_divsd_3(__asm_movsd_1(v1), v8), v8); // 0x40116b
        int64_t v10 = __asm_movsd(__asm_divsd(v9, __asm_movsd_1(0x4000000000000000))); // 0x40117c
        int128_t v11 = __asm_subsd(__asm_movsd_1(v10), v8); // 0x401186
        int64_t v12 = __asm_movsd(__asm_andpd(v11, __asm_movq_2(0x7fffffffffffffff))); // 0x401197
        v7 = __asm_movsd(__asm_movsd_1(v10));
        __asm_comisd(__asm_movsd_1(v12), v5);
    }
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/calc_2.c
// Address range: 0x4011c3 - 0x40120f
// Line range:    20 - 24
int main() {
    int64_t v1 = __asm_movsd(__asm_movsd_1(0x4083200000000000)); // 0x4011d3
    float64_t v2 = sqrtNewtonRaphson((float64_t)(int64_t)__asm_movq_2(v1)); // 0x4011e1
    int128_t v3 = __asm_movq_2(__asm_movq((int128_t)(int32_t)(float32_t)v2)); // 0x4011ef
    printf("The square root of %.2f is approximately %.5f\n", (float64_t)(int64_t)__asm_movq_2(v1), (float64_t)(int64_t)v3);
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 2

