//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

void increment(int32_t * value);

// --------------------- Global Variables ---------------------

char * g1 = "a\xec\x9d\x98 \xea\xb0\x92: %d\n"; // 0x402010

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/pointer_1.c
// Address range: 0x401126 - 0x401140
// Line range:    5 - 7
void increment(int32_t * value) {
    // 0x401126
    int64_t v1; // 0x401126
    *value = (int32_t)v1 + 1;
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/pointer_1.c
// Address range: 0x401140 - 0x401176
// Line range:    9 - 14
int main() {
    int32_t v1 = 10; // bp-12, 0x401148
    increment(&v1);
    printf((char *)&g1);
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 2

