//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/struct_1.c
// Address range: 0x401146 - 0x40124a
// Line range:    14 - 36
int main() {
    int64_t * mem = malloc(48); // 0x401153
    int64_t v1 = (int64_t)mem; // 0x401153
    int64_t * mem2 = malloc(48); // 0x401161
    int64_t * mem3 = malloc(48); // 0x40116f
    *mem = 0xa21646c726f57;
    *mem2 = 0x202c6f6c6c6548;
    int64_t v2 = (int64_t)mem3; // 0x40119a
    *mem3 = 0x2073692073696854;
    *(int64_t *)(v2 + 8) = 0xa21656572742061;
    *(char *)(v2 + 16) = 0;
    int64_t * v3 = (int64_t *)(v1 + 32); // 0x4011c5
    *v3 = (int64_t)mem2;
    int64_t * v4 = (int64_t *)(v1 + 40); // 0x4011d1
    *v4 = v2;
    printf("%s", (char *)*v3);
    printf("%s", mem);
    printf("%s", (char *)*v4);
    free(mem);
    free(mem2);
    free(mem3);
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 1

