//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;

// ------------------- Function Prototypes --------------------

float32_t add(float32_t a, float32_t b);
float32_t divide(float32_t a, float32_t b);
float32_t multiply(float32_t a, float32_t b);
float32_t subtract(float32_t a, float32_t b);

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/floating_point.c
// Address range: 0x401166 - 0x40131a
// Line range:    11 - 30
int main() {
    // 0x401166
    int128_t v1; // 0x401166
    int128_t v2 = v1;
    int128_t v3 = v1;
    int128_t v4 = v1;
    int128_t v5 = v1;
    int128_t v6 = v1;
    int128_t v7 = v1;
    srand(time(NULL));
    int32_t v8 = rand(); // 0x40117f
    __asm_pxor(v7, v7);
    int128_t v9 = __asm_cvtsi2ss(v8 % 100); // 0x4011a7
    int32_t v10 = __asm_movss(v9); // 0x4011ab
    int32_t v11 = rand() % 100;
    unsigned char v12 = llvm_ctpop_i8((char)v11); // 0x4011d0
    __asm_pxor(v9, v9);
    int128_t v13 = __asm_cvtsi2ss(v11); // 0x4011d8
    int32_t v14 = __asm_movss(v13); // 0x4011dc
    __asm_pxor(v13, v13);
    int128_t v15 = __asm_cvtss2sd(v14); // 0x4011e5
    __asm_pxor(v6, v6);
    int64_t v16 = __asm_movq(__asm_cvtss2sd(v10)); // 0x4011f3
    int128_t v17 = __asm_movapd(v15); // 0x4011f8
    printf("x = %.2f, y = %.2f\n\n", (float64_t)(int64_t)__asm_movq_1(v16), (float64_t)(int64_t)v17);
    int128_t v18 = __asm_movaps(__asm_movss_2(v14)); // 0x401218
    float32_t v19 = add((float32_t)(int32_t)__asm_movd(v10), (float32_t)(int32_t)v18); // 0x40121f
    __asm_pxor(v5, v5);
    int64_t v20 = __asm_movq(__asm_cvtss2sd_3((int128_t)(int32_t)v19)); // 0x40122c
    printf("Addition: %.2f\n", (float64_t)(int64_t)__asm_movq_1(v20));
    int128_t v21 = __asm_movaps(__asm_movss_2(v14)); // 0x40124d
    float32_t v22 = subtract((float32_t)(int32_t)__asm_movd(v10), (float32_t)(int32_t)v21); // 0x401254
    __asm_pxor(v4, v4);
    int64_t v23 = __asm_movq(__asm_cvtss2sd_3((int128_t)(int32_t)v22)); // 0x401261
    printf("Subtraction: %.2f\n", (float64_t)(int64_t)__asm_movq_1(v23));
    int128_t v24 = __asm_movaps(__asm_movss_2(v14)); // 0x401282
    float32_t v25 = multiply((float32_t)(int32_t)__asm_movd(v10), (float32_t)(int32_t)v24); // 0x401289
    __asm_pxor(v3, v3);
    int128_t v26 = __asm_movq_1(__asm_movq(__asm_cvtss2sd_3((int128_t)(int32_t)v25))); // 0x40129b
    printf("Multiplication: %.2f\n", (float64_t)(int64_t)v26);
    printf("Division: ");
    int128_t v27 = __asm_pxor(v26, v26); // 0x4012be
    __asm_ucomiss(v27, v14);
    if (v12 % 2 != 0) {
        // 0x4012c8
        __asm_ucomiss(__asm_pxor(v27, v27), v14);
        if (v11 == 0) {
            // 0x401309
            puts("Division by zero!");
            // 0x401313
            return 0;
        }
    }
    int128_t v28 = __asm_movaps(__asm_movss_2(v14)); // 0x4012da
    float32_t v29 = divide((float32_t)(int32_t)__asm_movd(v10), (float32_t)(int32_t)v28); // 0x4012e1
    __asm_pxor(v2, v2);
    int64_t v30 = __asm_movq(__asm_cvtss2sd_3((int128_t)(int32_t)v29)); // 0x4012ee
    printf("%.2f\n", (float64_t)(int64_t)__asm_movq_1(v30));
    // 0x401313
    return 0;
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/floating_point.c
// Address range: 0x40131a - 0x401334
// Line range:    33 - 35
float32_t add(float32_t a, float32_t b) {
    int64_t v1 = __asm_movss((int128_t)(int32_t)a); // 0x40131e
    int64_t v2 = __asm_movss((int128_t)(int32_t)b); // 0x401323
    int128_t v3 = __asm_movss_2((int32_t)v1); // 0x401328
    return (int32_t)__asm_addss(v3, (int32_t)v2);
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/floating_point.c
// Address range: 0x401334 - 0x40134e
// Line range:    37 - 39
float32_t subtract(float32_t a, float32_t b) {
    int64_t v1 = __asm_movss((int128_t)(int32_t)a); // 0x401338
    int64_t v2 = __asm_movss((int128_t)(int32_t)b); // 0x40133d
    int128_t v3 = __asm_movss_2((int32_t)v1); // 0x401342
    return (int32_t)__asm_subss(v3, (int32_t)v2);
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/floating_point.c
// Address range: 0x40134e - 0x401368
// Line range:    41 - 43
float32_t multiply(float32_t a, float32_t b) {
    int64_t v1 = __asm_movss((int128_t)(int32_t)a); // 0x401352
    int64_t v2 = __asm_movss((int128_t)(int32_t)b); // 0x401357
    int128_t v3 = __asm_movss_2((int32_t)v1); // 0x40135c
    return (int32_t)__asm_mulss(v3, (int32_t)v2);
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/floating_point.c
// Address range: 0x401368 - 0x40139c
// Line range:    45 - 50
float32_t divide(float32_t a, float32_t b) {
    int128_t v1 = a;
    int64_t v2 = __asm_movss(v1); // 0x40136c
    int32_t v3 = __asm_movss((int128_t)(int32_t)b); // 0x401371
    int128_t v4 = __asm_pxor(v1, v1); // 0x401376
    __asm_ucomiss(v4, v3);
    bool v5; // 0x401368
    if (v5) {
        // 0x40139a
        return (int32_t)__asm_divss(__asm_movss_2((int32_t)v2), v3);
    }
    int128_t v6 = __asm_pxor(v4, v4); // 0x401380
    __asm_ucomiss(v6, v3);
    if (!v5) {
        // 0x40139a
        return (int32_t)__asm_divss(__asm_movss_2((int32_t)v2), v3);
    }
    // 0x40139a
    return (int32_t)__asm_pxor(v6, v6);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 5

