//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/array_1.c
// Address range: 0x401136 - 0x4011b2
// Line range:    5 - 13
int main() {
    int32_t * ptr = (int32_t *)5; // bp-24, 0x40115a
    printf("%d ", 5);
    int64_t v1 = (int64_t)&ptr;
    for (int32_t i = 1; i < 5; i++) {
        // 0x401176
        v1 -= 4;
        printf("%d ", (int64_t)*(int32_t *)v1);
    }
    // 0x4011a1
    putchar(10);
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 1

