//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t * createNode(int32_t data);
void freeList(int32_t * head);
int32_t * merge(int32_t * left, int32_t * right);
int32_t * mergeSort(int32_t * head);
void printList(int32_t * head);

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linked_list_sort.c
// Address range: 0x401156 - 0x401196
// Line range:    12 - 18
int32_t * createNode(int32_t data) {
    int64_t * mem = malloc(24); // 0x401166
    int64_t v1 = (int64_t)mem; // 0x401166
    *(int32_t *)mem = data;
    *(int64_t *)(v1 + 8) = 0;
    *(int64_t *)(v1 + 16) = 0;
    return (int32_t *)mem;
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linked_list_sort.c
// Address range: 0x401196 - 0x401254
// Line range:    21 - 38
int32_t * merge(int32_t * left, int32_t * right) {
    // 0x401196
    if (left == NULL) {
        // 0x401252
        return right;
    }
    // 0x4011b6
    if (right == NULL) {
        // 0x401252
        return left;
    }
    int32_t * result; // 0x401196
    int64_t v1; // 0x401196
    if ((int32_t)v1 > (int32_t)v1) {
        int64_t v2 = (int64_t)right; // 0x401217
        int64_t * v3 = (int64_t *)(v2 + 16); // 0x401223
        int64_t v4 = (int64_t)merge(left, (int32_t *)*v3); // 0x401231
        *v3 = v4;
        *(int64_t *)(v4 + 8) = v2;
        result = right;
    } else {
        int64_t v5 = (int64_t)left; // 0x4011de
        int64_t * v6 = (int64_t *)(v5 + 16); // 0x4011ea
        int64_t v7 = (int64_t)merge((int32_t *)*v6, right); // 0x4011f8
        *v6 = v7;
        *(int64_t *)(v7 + 8) = v5;
        result = left;
    }
    // 0x401252
    return result;
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linked_list_sort.c
// Address range: 0x401254 - 0x401324
// Line range:    41 - 62
int32_t * mergeSort(int32_t * head) {
    // 0x401254
    if (head == NULL) {
        // 0x401322
        return NULL;
    }
    int64_t v1 = *(int64_t *)((int64_t)head + 16); // 0x40126b
    int32_t * v2 = head; // 0x401272
    if (v1 == 0) {
        // 0x401322
        return head;
    }
    int64_t v3 = *(int64_t *)(v1 + 16); // 0x4012ba
    while (v3 != 0) {
        // 0x401293
        v2 = (int32_t *)*(int64_t *)((int64_t)v2 + 16);
        int64_t v4 = *(int64_t *)(v3 + 16);
        if (v4 == 0) {
            // break -> 0x4012c3
            break;
        }
        v3 = *(int64_t *)(v4 + 16);
    }
    int64_t * v5 = (int64_t *)((int64_t)v2 + 16); // 0x4012cf
    int64_t v6 = *v5; // 0x4012cf
    *v5 = 0;
    *(int64_t *)(v6 + 8) = 0;
    int32_t * v7 = mergeSort(head); // 0x4012f6
    // 0x401322
    return merge(v7, mergeSort((int32_t *)v6));
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linked_list_sort.c
// Address range: 0x401324 - 0x401371
// Line range:    65 - 72
void printList(int32_t * head) {
    // 0x401324
    if (head == NULL) {
        // 0x401364
        putchar(10);
        return;
    }
    printf("%d ", (int64_t)*head);
    int64_t v1 = *(int64_t *)((int64_t)head + 16); // 0x401355
    int32_t * v2 = (int32_t *)v1; // 0x401362
    while (v1 != 0) {
        // 0x40133a
        printf("%d ", (int64_t)*v2);
        v1 = *(int64_t *)((int64_t)v2 + 16);
        v2 = (int32_t *)v1;
    }
    // 0x401364
    putchar(10);
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linked_list_sort.c
// Address range: 0x401371 - 0x4013aa
// Line range:    75 - 82
void freeList(int32_t * head) {
    // 0x401371
    if (head == NULL) {
        // 0x4013a6
        return;
    }
    int64_t v1 = *(int64_t *)((int64_t)head + 16); // 0x40138b
    free((int64_t *)head);
    int32_t * v2 = (int32_t *)v1; // 0x4013a4
    while (v1 != 0) {
        // 0x40137f
        v1 = *(int64_t *)((int64_t)v2 + 16);
        free((int64_t *)v2);
        v2 = (int32_t *)v1;
    }
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/linked_list_sort.c
// Address range: 0x4013aa - 0x4014a8
// Line range:    84 - 105
int main() {
    int32_t * v1 = createNode(5); // 0x4013b8
    int64_t v2 = (int64_t)v1; // 0x4013b8
    int64_t v3 = (int64_t)createNode(3); // 0x4013c6
    int64_t * v4 = (int64_t *)(v2 + 16); // 0x4013cf
    *v4 = v3;
    *(int64_t *)(v3 + 8) = v2;
    *(int64_t *)(*v4 + 16) = (int64_t)createNode(9);
    int64_t v5 = *v4; // 0x4013fd
    *(int64_t *)(*(int64_t *)(v5 + 16) + 8) = v5;
    *(int64_t *)(*(int64_t *)(*v4 + 16) + 16) = (int64_t)createNode(1);
    int64_t v6 = *(int64_t *)(*v4 + 16); // 0x40143b
    *(int64_t *)(*(int64_t *)(v6 + 16) + 8) = v6;
    printf("Original List: ");
    printList(v1);
    int32_t * v7 = mergeSort(v1); // 0x40146d
    printf("Sorted List: ");
    printList(v7);
    freeList(v7);
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 6

