//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

void sort(int32_t * array, int32_t n, int32_t (*compare)(int32_t *, int32_t *));

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/func_pointer_2.c
// Address range: 0x401182 - 0x4011b6
// Line range:    14 - 16
void sort(int32_t * array, int32_t n, int32_t (*compare)(int32_t *, int32_t *)) {
    // 0x401182
    qsort((int64_t *)array, n, 4, (int32_t (*)(int64_t *, int64_t *))compare);
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/func_pointer_2.c
// Address range: 0x4011b6 - 0x4012a7
// Line range:    18 - 34
int main() {
    int64_t v1 = 5; // bp-40, 0x4011be
    sort((int32_t *)&v1, 6, (int32_t (*)(int32_t *, int32_t *))0x401146);
    printf("Ascending: ");
    int64_t v2; // bp-8, 0x4011b6
    int64_t v3 = (int64_t)&v2 - 32;
    for (int64_t i = 0; i < 6; i++) {
        // 0x401216
        printf("%d ", (int64_t)*(int32_t *)(4 * i + v3));
    }
    // 0x40123a
    putchar(10);
    sort((int32_t *)&v1, 6, (int32_t (*)(int32_t *, int32_t *))0x401164);
    printf("Descending: ");
    for (int64_t i = 0; i < 6; i++) {
        // 0x401272
        printf("%d ", (int64_t)*(int32_t *)(4 * i + v3));
    }
    // 0x401296
    putchar(10);
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 2

