//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

int32_t factorial(int32_t n);
bool run_tests(void);

// ------------------------ Functions -------------------------

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/factorial.c
// Address range: 0x401126 - 0x40115e
// Line range:    6 - 13
int32_t factorial(int32_t n) {
    // 0x401126
    if (n < 0) {
        // 0x40115c
        return 0;
    }
    int32_t result = 1; // 0x401142
    if (n != 0) {
        // 0x40114b
        result = factorial(n - 1) * n;
    }
    // 0x40115c
    return result;
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/factorial.c
// Address range: 0x40115e - 0x4011cc
// Line range:    16 - 28
bool run_tests(void) {
    // 0x40115e
    if (factorial(0) != 1 || factorial(5) != 120 || factorial(6) != 720) {
        // 0x4011ca
        return false;
    }
    bool result = false; // 0x4011a7
    if (factorial(10) == 0x375f00) {
        // 0x4011b0
        result = factorial(-5) == 0;
    }
    // 0x4011ca
    return result;
}

// From module:   /home/hyeyoo/lifting/binary-lifting-testcases/src/factorial.c
// Address range: 0x4011cc - 0x4011fb
// Line range:    30 - 39
int main() {
    // 0x4011cc
    if (!run_tests()) {
        // 0x4011ea
        puts("Some test cases failed.");
    } else {
        // 0x4011de
        puts("All test cases passed!");
    }
    // 0x4011f4
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 3

